#pragma once
struct InvData
{
	int n;
	int r;
	const char * name;
	InvData(const char * name, int n, int r) : n(n), r(r), name(name){};
};
void measure(void(*measure_invocation)(void(*ff)(), InvData));
void clean_100();
void measure_invocation_100(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_110();
void measure_invocation_110(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_120();
void measure_invocation_120(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_130();
void measure_invocation_130(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_140();
void measure_invocation_140(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_150();
void measure_invocation_150(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_160();
void measure_invocation_160(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_170();
void measure_invocation_170(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_180();
void measure_invocation_180(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_190();
void measure_invocation_190(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_200();
void measure_invocation_200(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_210();
void measure_invocation_210(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_220();
void measure_invocation_220(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_230();
void measure_invocation_230(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_240();
void measure_invocation_240(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_250();
void measure_invocation_250(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_260();
void measure_invocation_260(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_270();
void measure_invocation_270(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_280();
void measure_invocation_280(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_290();
void measure_invocation_290(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_300();
void measure_invocation_300(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_310();
void measure_invocation_310(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_320();
void measure_invocation_320(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_330();
void measure_invocation_330(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_340();
void measure_invocation_340(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_350();
void measure_invocation_350(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_360();
void measure_invocation_360(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_370();
void measure_invocation_370(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_380();
void measure_invocation_380(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_390();
void measure_invocation_390(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_400();
void measure_invocation_400(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_410();
void measure_invocation_410(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_420();
void measure_invocation_420(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_430();
void measure_invocation_430(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_440();
void measure_invocation_440(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_450();
void measure_invocation_450(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_460();
void measure_invocation_460(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_470();
void measure_invocation_470(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_480();
void measure_invocation_480(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_490();
void measure_invocation_490(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_500();
void measure_invocation_500(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_510();
void measure_invocation_510(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_520();
void measure_invocation_520(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_530();
void measure_invocation_530(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_540();
void measure_invocation_540(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_550();
void measure_invocation_550(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_560();
void measure_invocation_560(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_570();
void measure_invocation_570(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_580();
void measure_invocation_580(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_590();
void measure_invocation_590(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_600();
void measure_invocation_600(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_610();
void measure_invocation_610(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_620();
void measure_invocation_620(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_630();
void measure_invocation_630(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_640();
void measure_invocation_640(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_650();
void measure_invocation_650(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_660();
void measure_invocation_660(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_670();
void measure_invocation_670(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_680();
void measure_invocation_680(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_690();
void measure_invocation_690(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_700();
void measure_invocation_700(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_710();
void measure_invocation_710(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_720();
void measure_invocation_720(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_730();
void measure_invocation_730(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_740();
void measure_invocation_740(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_750();
void measure_invocation_750(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_760();
void measure_invocation_760(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_770();
void measure_invocation_770(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_780();
void measure_invocation_780(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_790();
void measure_invocation_790(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_800();
void measure_invocation_800(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_810();
void measure_invocation_810(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_820();
void measure_invocation_820(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_830();
void measure_invocation_830(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_840();
void measure_invocation_840(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_850();
void measure_invocation_850(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_860();
void measure_invocation_860(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_870();
void measure_invocation_870(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_880();
void measure_invocation_880(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_890();
void measure_invocation_890(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_900();
void measure_invocation_900(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_910();
void measure_invocation_910(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_920();
void measure_invocation_920(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_930();
void measure_invocation_930(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_940();
void measure_invocation_940(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_950();
void measure_invocation_950(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_960();
void measure_invocation_960(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_970();
void measure_invocation_970(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_980();
void measure_invocation_980(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_990();
void measure_invocation_990(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1000();
void measure_invocation_1000(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1010();
void measure_invocation_1010(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1020();
void measure_invocation_1020(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1030();
void measure_invocation_1030(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1040();
void measure_invocation_1040(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1050();
void measure_invocation_1050(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1060();
void measure_invocation_1060(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1070();
void measure_invocation_1070(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1080();
void measure_invocation_1080(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1090();
void measure_invocation_1090(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1100();
void measure_invocation_1100(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1110();
void measure_invocation_1110(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1120();
void measure_invocation_1120(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1130();
void measure_invocation_1130(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1140();
void measure_invocation_1140(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1150();
void measure_invocation_1150(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1160();
void measure_invocation_1160(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1170();
void measure_invocation_1170(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1180();
void measure_invocation_1180(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1190();
void measure_invocation_1190(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1200();
void measure_invocation_1200(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1210();
void measure_invocation_1210(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1220();
void measure_invocation_1220(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1230();
void measure_invocation_1230(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1240();
void measure_invocation_1240(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1250();
void measure_invocation_1250(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1260();
void measure_invocation_1260(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1270();
void measure_invocation_1270(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1280();
void measure_invocation_1280(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1290();
void measure_invocation_1290(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1300();
void measure_invocation_1300(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1310();
void measure_invocation_1310(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1320();
void measure_invocation_1320(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1330();
void measure_invocation_1330(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1340();
void measure_invocation_1340(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1350();
void measure_invocation_1350(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1360();
void measure_invocation_1360(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1370();
void measure_invocation_1370(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1380();
void measure_invocation_1380(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1390();
void measure_invocation_1390(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1400();
void measure_invocation_1400(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1410();
void measure_invocation_1410(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1420();
void measure_invocation_1420(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1430();
void measure_invocation_1430(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1440();
void measure_invocation_1440(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1450();
void measure_invocation_1450(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1460();
void measure_invocation_1460(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1470();
void measure_invocation_1470(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1480();
void measure_invocation_1480(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1490();
void measure_invocation_1490(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
void clean_1500();
void measure_invocation_1500(void(*f)(), InvData data, void(*callback)(void(*ff)(), InvData));
